name: folding-dssp
channels:
  - salilab
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - python=3.9
  - biopython
  - pandas
  - numpy
  - requests
  - dssp
  - jupyterlab  # optional but helpful
  - pytest # optional but helpful